# Generated by Django 2.2.1 on 2019-08-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url_model',
            name='empolyer',
            field=models.CharField(default='appnies', max_length=100),
        ),
    ]
